# Generated by Django 4.0.8 on 2022-10-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_rename_issue_lend'),
    ]

    operations = [
        migrations.AddField(
            model_name='lend',
            name='is_currently_lending',
            field=models.BooleanField(default=True),
        ),
    ]
