# Generated by Django 4.0.8 on 2022-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_lend_is_currently_lending'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_lending',
            field=models.IntegerField(default=0),
        ),
    ]
